name: Deploy

on:
  push:
    tags: [ '*.*.*' ]

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install CLI
        run: curl -fsSL https://downloads.slack-edge.com/slack-cli/install.sh | bash

      - name: Deploy
        env:
          SLACK_TOKEN: ${{ secrets.SlackService }}
          APP: ${{ secrets.app }}
          WORKSPACE: ${{ secrets.workspace }}
        run: slack deploy -s --no-color --token $SLACK_TOKEN --app $APP --workspace $WORKSPACE
